baseURL = 'https://emaniaditya.github.io/'
languageCode = 'en-us'
title = 'E S Aaditya Reddy'
theme = 'hugo-bearblog'

[[menu.main]]
  name = "home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "blog"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "projects"
  url = "/projects/"
  weight = 3

[[menu.main]]
  name = "resume"
  url = "/resume.pdf"
  weight = 4

[params]
  description = "Software Developer | MERN | Node.js"
  author = "E S Aaditya Reddy"
  hideMadeWithLine = true
  favicon = "favicon.svg"

  [params.social]
    email = "esaadityareddy@gmail.com"
    github = "https://github.com/EmaniAditya"
    linkedin = "https://linkedin.com/in/emaniaditya"
    x = "https://x.com/Emani_Aditya"

[taxonomies]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
